FROM python:3.8-slim

WORKDIR /app
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 make -y
RUN pip install --upgrade pip && pip install torch==1.12.1+cpu torchvision==0.13.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu

COPY ./src/requirements.txt requirements.txt
RUN pip install -r requirements.txt

